import configparser
import os
from dotenv import load_dotenv
load_dotenv()

config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../eclient.cfg')
print(config_path)
cfg = configparser.ConfigParser()
cfg.read(config_path)
MOCK_MODE = cfg.getboolean('DEFAULT', 'MOCK_MODE', fallback=True)
PYWEBVIEW_GUI = cfg.get('DEFAULT', 'PYWEBVIEW_GUI', fallback='qt')
DEFAULT_HOST = cfg.get('DEFAULT', 'DEFAULT_HOST', fallback='127.0.0.1')
TRADING_PORT = cfg.getint('DEFAULT', 'TRADING_PORT', fallback=7497)
DEFAULT_CLIENT_ID = cfg.getint('DEFAULT', 'DEFAULT_CLIENT_ID', fallback=0)
INITIAL_SYMBOL = cfg.get('DEFAULT', 'INITIAL_SYMBOL', fallback='AAPL')
DEFAULT_TIMEFRAME = cfg.get('DEFAULT', 'DEFAULT_TIMEFRAME', fallback='1 hour')
DEFAULT_TIMEFRAME_OPTIONS = tuple(opt.strip() for opt in cfg.get('DEFAULT', 'DEFAULT_TIMEFRAME_OPTIONS', fallback='30 secs,1 min,5 min,15 min,1 hour').split(','))
DEFAULT_HISTORICAL_DURATION = cfg.get('DEFAULT', 'DEFAULT_HISTORICAL_DURATION', fallback='30 D')
CONTRACT_EXCHANGE = cfg.get('DEFAULT', 'CONTRACT_EXCHANGE', fallback='SMART')
DEFAULT_CURRENCY = cfg.get('DEFAULT', 'DEFAULT_CURRENCY', fallback='USD')
SEC_TYPE = cfg.get('DEFAULT', 'SEC_TYPE', fallback='STK')
USE_RTH = cfg.getint('DEFAULT', 'USE_RTH', fallback=1)
WHAT_TO_SHOW = cfg.get('DEFAULT', 'WHAT_TO_SHOW', fallback='TRADES')
SMA_SHORT_PERIOD = cfg.getint('DEFAULT', 'SMA_SHORT_PERIOD', fallback=20)
SMA_LONG_PERIOD = cfg.getint('DEFAULT', 'SMA_LONG_PERIOD', fallback=50)
SMA_SHORT_COLOR = cfg.get('DEFAULT', 'SMA_SHORT_COLOR', fallback='blue')
SMA_LONG_COLOR = cfg.get('DEFAULT', 'SMA_LONG_COLOR', fallback='red')
SCAN_CODE = cfg.get('DEFAULT', 'SCAN_CODE', fallback='Top Percent Gainers')
